CREATE DATABASE IF NOT EXISTS aéroport;
USE aéroport;

CREATE TABLE AEROPORT(
   CODE_AEROPORT INT PRIMARY KEY,
   NOM_AEROPORT VARCHAR(100),
   VILLE VARCHAR(50),
   PAYS VARCHAR(50)
);

CREATE TABLE PILOTE(
   ID_PIL INT PRIMARY KEY,
   NOM_PIL VARCHAR(50),
   PRENOM_PIL VARCHAR(50),
   DATE_NAISSANCE_PIL DATE,
   ADRESSE VARCHAR(50),
   SALAIRE DECIMAL(10,2),
   PRIME DECIMAL(10,2),
   GRADE_PIL VARCHAR(30),
   NUM_LICENCE CHAR(10),
   DATE_VALIDITE_LICENCE DATE,
   ID_PIL_ENCADRE INT,
   FOREIGN KEY (ID_PIL_ENCADRE) REFERENCES PILOTE(ID_PIL)
);

CREATE TABLE RESERVATION(
   CODE_RES INT PRIMARY KEY,
   DATE_RES DATE,
   PLACE VARCHAR(15),
   CLASSE_VOYAGE VARCHAR(15),
   TARIF DECIMAL(10,2),
   STATUT_RES VARCHAR(20)
);

CREATE TABLE TERMINAL(
   CODE_RES INT,
   NUM_TERMINAL INT,
   NUM_PORTE_EMBARQUEMENT VARCHAR(50),
   PRIMARY KEY (CODE_RES, NUM_TERMINAL),
   FOREIGN KEY (CODE_RES) REFERENCES RESERVATION(CODE_RES)
);

CREATE TABLE COMPAGNIE(
   ID_COMPAGNIE INT PRIMARY KEY,
   PAYS_COMPAGNIE VARCHAR(50),
   NOM_COMPAGNIE VARCHAR(100)
);

CREATE TABLE PISTE(
   ID_PISTE INT PRIMARY KEY,
   LONGUEUR_PISTE INT,
   TYPE_SURFACE VARCHAR(30),
   ETAT_PISTE VARCHAR(20),
   CODE_AEROPORT INT NOT NULL,
   FOREIGN KEY (CODE_AEROPORT) REFERENCES AEROPORT(CODE_AEROPORT)
);

CREATE TABLE BILLET(
   ID_BILLET INT PRIMARY KEY,
   CLASSE_BILLET VARCHAR(20),
   TARIF_BILLET DECIMAL(10,2),
   CODE_RES INT NOT NULL,
   FOREIGN KEY (CODE_RES) REFERENCES RESERVATION(CODE_RES)
);

CREATE TABLE PAIEMENT(
   ID_BILLET INT,
   ID_PAIEMENT INT,
   MODE_PAIEMENT VARCHAR(20),
   DATE_PAIEMENT DATE,
   MONTANT_PAIEMENT DECIMAL(10,2),
   PRIMARY KEY (ID_BILLET, ID_PAIEMENT),
   FOREIGN KEY (ID_BILLET) REFERENCES BILLET(ID_BILLET)
);

CREATE TABLE SERVICE_ADDITIONNEL(
   CODE_RES INT,
   ID_SERVICE INT,
   SERVICE_ADI VARCHAR(50),
   PRIX_SERVICE DECIMAL(10,2),
   PRIMARY KEY (CODE_RES, ID_SERVICE),
   FOREIGN KEY (CODE_RES) REFERENCES RESERVATION(CODE_RES)
);

CREATE TABLE AVION(
   NUM_AV INT PRIMARY KEY,
   TYPE_AV VARCHAR(30),
   MODELE_AV VARCHAR(50),
   CAPACITE INT,
   STATUT_OPERATIONNEL VARCHAR(20),
   ID_COMPAGNIE INT NOT NULL,
   FOREIGN KEY (ID_COMPAGNIE) REFERENCES COMPAGNIE(ID_COMPAGNIE)
);

CREATE TABLE VOL(
   NUM_VOL CHAR(10) PRIMARY KEY,
   DATE_DEPART_PREVU DATE,
   DATE_ARRIVEE_PREVU DATE,
   HEURE_DEPART_PREVU TIME,
   HEURE_ARRIVEE_PREVU TIME,
   STATUT_VOL VARCHAR(20),
   ID_PIL INT NOT NULL,
   NUM_AV INT NOT NULL,
   ID_COMPAGNIE INT NOT NULL,
   CODE_AEROPORT INT NOT NULL,
   CODE_AEROPORT_1 INT NOT NULL,
   FOREIGN KEY (ID_PIL) REFERENCES PILOTE(ID_PIL),
   FOREIGN KEY (NUM_AV) REFERENCES AVION(NUM_AV),
   FOREIGN KEY (ID_COMPAGNIE) REFERENCES COMPAGNIE(ID_COMPAGNIE),
   FOREIGN KEY (CODE_AEROPORT) REFERENCES AEROPORT(CODE_AEROPORT),
   FOREIGN KEY (CODE_AEROPORT_1) REFERENCES AEROPORT(CODE_AEROPORT)
);

CREATE TABLE PASSAGER(
   ID_PASS INT PRIMARY KEY,
   NOM_PASS VARCHAR(50),
   EMAIL VARCHAR(50),
   TELEPHONE VARCHAR(50),
   PRENOM_PASS VARCHAR(50),
   DATE_NAISSANCE DATE,
   NATIONALITE VARCHAR(50),
   PROGRAMME_FIDELITE VARCHAR(20),
   PASSEPORT_NB VARCHAR(20),
   DEMANDE_SPECIAL VARCHAR(100),
   NUM_VOL CHAR(10) NOT NULL,
   FOREIGN KEY (NUM_VOL) REFERENCES VOL(NUM_VOL)
);

CREATE TABLE BAGAGE(
   ID_PASS INT,
   ID_BAG INT,
   POIDS DECIMAL(5,2),
   SURTAXE VARCHAR(50),
   TYPE_BAGAGE VARCHAR(10),
   STATUT_BAGAGE VARCHAR(20),
   PRIMARY KEY (ID_PASS, ID_BAG),
   FOREIGN KEY (ID_PASS) REFERENCES PASSAGER(ID_PASS)
);

CREATE TABLE MAINTENANCE(
   NUM_AV INT,
   ID_MAINT INT,
   DATE_MAINT DATE,
   TYPE_MAINT VARCHAR(50),
   COUT DECIMAL(10,2),
   PRIMARY KEY (NUM_AV, ID_MAINT),
   FOREIGN KEY (NUM_AV) REFERENCES AVION(NUM_AV)
);

CREATE TABLE LIEE_A(
   NUM_VOL CHAR(10),
   CODE_RES INT,
   PRIMARY KEY (NUM_VOL, CODE_RES),
   FOREIGN KEY (NUM_VOL) REFERENCES VOL(NUM_VOL),
   FOREIGN KEY (CODE_RES) REFERENCES RESERVATION(CODE_RES)
);

CREATE TABLE VOL_ESCALE_AEROPORT(
   CODE_AEROPORT INT,
   NUM_VOL CHAR(10),
   ID_PISTE INT,
   HEURE_ARRIVEE_ESCALE TIME,
   HEURE_DEPART_ESCALE TIME,
   PRIMARY KEY (CODE_AEROPORT, NUM_VOL, ID_PISTE),
   FOREIGN KEY (CODE_AEROPORT) REFERENCES AEROPORT(CODE_AEROPORT),
   FOREIGN KEY (NUM_VOL) REFERENCES VOL(NUM_VOL),
   FOREIGN KEY (ID_PISTE) REFERENCES PISTE(ID_PISTE)
);

SHOW TABLES;

DESCRIBE AEROPORT;
DESCRIBE PILOTE;
DESCRIBE RESERVATION;
DESCRIBE TERMINAL;
DESCRIBE COMPAGNIE;
DESCRIBE PISTE;
DESCRIBE BILLET;
DESCRIBE PAIEMENT;
DESCRIBE SERVICE_ADDITIONNEL;
DESCRIBE AVION;
DESCRIBE VOL;
DESCRIBE PASSAGER;
DESCRIBE BAGAGE;
DESCRIBE MAINTENANCE;
DESCRIBE LIEE_A;
DESCRIBE VOL_ESCALE_AEROPORT;