USE aéroport;

ALTER TABLE BILLET
ADD CONSTRAINT chk_tarif_billet CHECK (TARIF_BILLET >= 0);


ALTER TABLE PAIEMENT
ADD CONSTRAINT chk_montant_paiement CHECK (MONTANT_PAIEMENT >= 0);


ALTER TABLE SERVICE_ADDITIONNEL
ADD CONSTRAINT chk_prix_service CHECK (PRIX_SERVICE >= 0);


ALTER TABLE MAINTENANCE
ADD CONSTRAINT chk_cout_maintenance CHECK (COUT >= 0);


ALTER TABLE BAGAGE
ADD CONSTRAINT chk_poids_bagage CHECK (POIDS BETWEEN 0 AND 50);


ALTER TABLE VOL
ADD CONSTRAINT chk_statut_vol CHECK (STATUT_VOL IN ('Prévu', 'En vol', 'Arrivé', 'Annulé'));


ALTER TABLE AVION
ADD CONSTRAINT chk_statut_avion CHECK (STATUT_OPERATIONNEL IN ('Actif', 'En maintenance', 'Retiré'));


ALTER TABLE RESERVATION
ADD CONSTRAINT chk_statut_res CHECK (STATUT_RES IN ('Confirmée', 'Annulée', 'En attente'));


ALTER TABLE PASSAGER
ADD CONSTRAINT chk_email_pass CHECK (EMAIL LIKE '%@%.%');
